server:
  port: 8083
spring:
  application:
    name: infytel-plan
  cloud:
    consul:
      discovery:
        hostname: localhost
      config:
        enabled: true
        prefix: config
        defaultContext: application
        profileSeparator: '::'
        format: YAML